# Morphological operation

In [5]:
import cv2    
import numpy as np

In [14]:
img = cv2.imread("images.png")
img = cv2.resize(img , (500,500))

m = np.ones((15,15),np.int8)
print(m)

er = cv2.erode(img , m , iterations=1)
di = cv2.dilate(img , m , iterations=1)

cv2.imshow("morphological" , img)
cv2.imshow("erode" , er)
cv2.imshow("dilate" , di)
cv2.imshow("dilate" , di)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [13]:
# Exmachina 

In [25]:
img = cv2.imread("morph_close.png")
img = cv2.resize(img , (500,500))

k = np.ones((30,30),np.int8)

#op = cv2.morphologyEx(img , cv2.MORPH_OPEN , k , iterations=1)
# cl = cv2.morphologyEx(img , cv2.MORPH_CLOSE , k , iterations=1)
# gr = cv2.morphologyEx(img , cv2.MORPH_GRADIENT , k , iterations=1)
# tp = cv2.morphologyEx(img , cv2.MORPH_TOPHAT , k , iterations=1)
tp = cv2.morphologyEx(img , cv2.MORPH_BLACKHAT , k , iterations=1)
cv2.imshow("org" , img)
cv2.imshow("morphologyEx" , tp)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Image Pyramid

In [29]:
img = cv2.imread("WhatsApp Image 2024-08-30 at 10.03.11 PM.jpeg")
img = cv2.resize(img , (500,500))



cv2.imshow("img" , img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [33]:
img = cv2.imread("WhatsApp Image 2024-08-30 at 10.03.11 PM.jpeg")
print(img.shape)

new = cv2.pyrDown(img)
print(new.shape)

new1 = cv2.pyrDown(new)
print(new1.shape)

new2 = cv2.pyrDown(new1)
print(new2.shape)

big_img = cv2.pyrUp(new1)
print(big_img.shape)
# cv2.imshow("img" , img)
# cv2.imshow("img1" , new)
# cv2.imshow("img2" , new1)
cv2.imshow("img3" , new1)
cv2.imshow("big img" , big_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

(4160, 3120, 3)
(2080, 1560, 3)
(1040, 780, 3)
(520, 390, 3)
(2080, 1560, 3)


# Image Translation 

In [34]:
import numpy as np

In [35]:
img = cv2.imread("WhatsApp Image 2024-08-30 at 10.03.11 PM.jpeg")
img = cv2.resize(img , (500,500))

m = np.float32([[1,0,100], [0,1,50]])

new = cv2.warpAffine(img , m , (500 , 500))

cv2.imshow("img translation " , img)
cv2.imshow("img translation1 " , m)
cv2.imshow("img translation2 " , new)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Geometric Transformations

# BackGround Subtraction

In [38]:
cap = cv2.VideoCapture(r"G:\final-1.mp4")

sub_m = cv2.createBackgroundSubtractorMOG2()

while cap.isOpened():
    r , frame = cap.read()
    if r == True:
        frame = cv2.resize(frame , (700,500))
        sub_v = sub_m.apply(frame)
        cv2.imshow("background" , sub_v)
        cv2.imshow("video", frame )
        if cv2.waitKey(25) & 0xff == ord("p"):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()

# Extract images from video using OpenCV

In [1]:
import cv2

In [2]:
cap = cv2.VideoCapture(r"G:\final-1.mp4")
c=0
while True :
    r , frame = cap.read()
    if r == True:
        frame = cv2.resize(frame , (500 , 500))
        filename = "G://org_img"+str(c) + "png"
        cv2.imwrite(filename , frame) 
        cv2.imshow("extract images", frame)
        c=c+1
        if cv2.waitKey(25) & 0xff == ord("p"):
            break
    else :
        break
cap.release()
cv2.destroyAllWindows()

error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:708: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'cv::imwrite_'


In [7]:
import cv2

# Capture the video
cap = cv2.VideoCapture(r"G:\final-1.mp4")
c = 0

# Loop to extract frames
while True:
    r, frame = cap.read()
    if r:
        # Resize the frame to 500x500 pixels
        frame = cv2.resize(frame, (500, 500))
        
        # Correct the filename by adding a period before 'png'
        filename = "G://org_img" + str(c) + ".png"
        
        # Save the current frame as an image
        cv2.imwrite(filename, frame)
        
        # Display the frame
        cv2.imshow("extract images", frame)
        
        # Increment the frame counter
        c = c + 1
        
        # Break the loop if the 'p' key is pressed
        if cv2.waitKey(25) & 0xFF == ord('p'):
            break
    else:
        break

# Release the video capture object and close all windows
cap.release()
cv2.destroyAllWindows()


# cvtColor method in opencv

In [3]:
import cv2 

In [9]:
img = cv2.imread("WhatsApp Image 2024-08-30 at 10.03.11 PM.jpeg")
img = cv2.resize(img , (500,500))

new = cv2.cvtColor(img ,cv2.COLOR_BGR2LAB )


cv2.imshow("org", img)
cv2.imshow("new", new)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Crop image in opencv

In [14]:
import cv2 

img = cv2.imread("WhatsApp Image 2024-08-30 at 10.03.11 PM.jpeg")
img = cv2.resize(img , (500,500))

print(img.shape)

crop = img[120:200,:400]


cv2.imshow("org", img)
cv2.imshow("new", crop)
cv2.waitKey(0)
cv2.destroyAllWindows()


(500, 500, 3)


# Create blank Image 

In [1]:
import cv2 
import numpy as np

img = cv2.imread("WhatsApp Image 2024-08-30 at 10.03.11 PM.jpeg")
img = cv2.resize(img , (500,500))

print(img.shape)
new = np.ones((500 ,500 ,3) , np.uint8)*255



cv2.imshow("org", img)
cv2.imshow("new",new )
cv2.waitKey(0)
cv2.destroyAllWindows()


(500, 500, 3)


In [15]:
print(img)

[[[141 161 203]
  [143 162 205]
  [143 162 205]
  ...
  [190 213 255]
  [195 214 254]
  [149 180 229]]

 [[142 161 204]
  [142 161 204]
  [142 161 204]
  ...
  [195 214 253]
  [196 215 252]
  [140 175 229]]

 [[140 161 206]
  [141 162 207]
  [141 163 205]
  ...
  [207 221 252]
  [192 212 255]
  [124 163 229]]

 ...

 [[170  78   0]
  [170  78   0]
  [170  78   0]
  ...
  [175 177 195]
  [175 177 195]
  [161 165 177]]

 [[175  75   1]
  [168  76   0]
  [169  75   0]
  ...
  [175 178 192]
  [175 177 195]
  [158 163 172]]

 [[168  73   3]
  [158  68   4]
  [158  64   4]
  ...
  [183 186 200]
  [180 183 200]
  [167 172 181]]]


In [3]:
import cv2 
import numpy as np

img = cv2.imread("WhatsApp Image 2024-08-30 at 10.03.11 PM.jpeg")
img = cv2.resize(img , (500,500))

print(img.shape)
new = np.zeros((500 ,500 ,3) , np.uint8)*255



cv2.imshow("org", img)
cv2.imshow("new",new )
cv2.waitKey(0)
cv2.destroyAllWindows()


(500, 500, 3)


# ColorPicker

In [4]:
import cv2
import numpy as np

# Load and resize the image
img = cv2.imread("WhatsApp Image 2024-08-30 at 10.03.11 PM.jpeg")
img = cv2.resize(img, (500, 500))

# Create a black image to display the selected color
new = np.zeros((500, 500, 3), np.uint8)

# Mouse click event to capture the color
def pick_color(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:  # On left mouse click
        # Get the color at the clicked pixel
        color_bgr = img[y, x]
        # Fill the 'new' image with the selected color
        new[:] = color_bgr
        # Display the selected color in the "new" window
        cv2.imshow("new", new)
        print(f"BGR Color at ({x}, {y}): {color_bgr}")

# Show the original image
cv2.imshow("org", img)

# Set the mouse callback to capture the color on click
cv2.setMouseCallback("org", pick_color)

# Keep the windows open until 'Esc' is pressed
while True:
    if cv2.waitKey(1) & 0xFF == 27:  # Press 'Esc' to exit
        break

cv2.destroyAllWindows()


BGR Color at (161, 0): [138 161 212]


In [5]:
import cv2
import numpy as np

# Load and resize the image
img = cv2.imread("WhatsApp Image 2024-08-30 at 10.03.11 PM.jpeg")
img = cv2.resize(img, (500, 500))

# Create a blank black image where the color will be displayed
new = np.zeros((500, 500, 3), np.uint8)

# Callback function for trackbar (does nothing here but is required)
def nothing(x):
    pass

# Create a window
cv2.namedWindow('new')

# Create trackbars for color change
cv2.createTrackbar('R', 'new', 0, 255, nothing)
cv2.createTrackbar('G', 'new', 0, 255, nothing)
cv2.createTrackbar('B', 'new', 0, 255, nothing)

# Loop to update the image color based on trackbar position
while True:
    # Get the current positions of the trackbars
    r = cv2.getTrackbarPos('R', 'new')
    g = cv2.getTrackbarPos('G', 'new')
    b = cv2.getTrackbarPos('B', 'new')

    # Update the new image with the selected color
    new[:] = [b, g, r]  # BGR format

    # Display the original and modified images
    cv2.imshow("org", img)
    cv2.imshow("new", new)

    # Break the loop when 'Esc' key is pressed
    if cv2.waitKey(1) & 0xFF == 27:
        break

cv2.destroyAllWindows()


# getTrackbarPos() function in opencv

In [6]:
import cv2
import numpy as np

# Callback function for the trackbar (does nothing but is required)
def nothing(x):
    pass

# Create a black image
img = np.zeros((300, 512, 3), np.uint8)

# Create a window
cv2.namedWindow('image')

# Create trackbars for color change
cv2.createTrackbar('R', 'image', 0, 255, nothing)
cv2.createTrackbar('G', 'image', 0, 255, nothing)
cv2.createTrackbar('B', 'image', 0, 255, nothing)

# Infinite loop to update the image based on trackbar position
while True:
    # Get the current positions of the trackbars
    r = cv2.getTrackbarPos('R', 'image')
    g = cv2.getTrackbarPos('G', 'image')
    b = cv2.getTrackbarPos('B', 'image')

    # Update the image color based on the trackbar positions
    img[:] = [b, g, r]  # Set the entire image to the selected color

    # Display the image
    cv2.imshow('image', img)

    # Break the loop when the 'Esc' key is pressed
    if cv2.waitKey(1) & 0xFF == 27:  # 'Esc' key
        break

# Clean up and close the window
cv2.destroyAllWindows()
