In [1]:
import numpy as np

In [2]:
import matplotlib

In [3]:
import pandas 

In [4]:
import os 

In [5]:
import cv2 

In [6]:
import cv2
print(cv2.__version__)

4.10.0


In [7]:
import cv2
import sys

print(f"Python version: {sys.version}")
print(f"OpenCV version: {cv2.__version__}")


Python version: 3.8.19 (default, Mar 20 2024, 19:55:45) [MSC v.1916 64 bit (AMD64)]
OpenCV version: 4.10.0


In [7]:
path = r"C:\Users\Mega Computers\Pictures\chris-ried-sqJ40H9RtNw-unsplash.jpg"
img = cv2.imread(path)

cv2.imshow('image=' ,img)

cv2.waitKey(0)

cv2.destroyAllWindows()

In [8]:
img = cv2.imread(path)

img = cv2.resize(img , (600 ,400))

cv2.imshow('image=' ,img)

cv2.waitKey(0)

cv2.destroyAllWindows()

In [10]:
img = cv2.imread("WhatsApp Image 2024-08-30 at 10.03.11 PM.jpeg") # image read 
re = cv2.resize(img , (600 , 600))
cv2.imshow("Eisa" ,re)# image show 
cv2.imshow("Eisa 1 " ,img)     
cv2.waitKey(0)             # image frame wait time ms and 0 pass keyborad any key press 
cv2.destroyAllWindows()       # all windows close 
#cv2.destroyWindow("Eisa 1 ")           # only one window close 


# Show Multiple Image and Slide Show 

In [9]:
img = cv2.imread(r"C:\Users\Mega Computers\Pictures\dennis-buchner-elk8DRDVYLI-unsplash.jpg")
re_img = cv2.resize(img , (800 , 500))
cv2.imshow("coder" , re_img)
cv2.waitKey(0)
cv2.destroyAllWindows() 
# cv2.destoryAllWindows()

In [18]:
v = np.array([1,2,3,1,2,3])
np.hstack((v,v))


array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [11]:
img = cv2.imread("WhatsApp Image 2024-08-30 at 10.03.11 PM.jpeg") # image read 
print(img) # RGB

[[[141 160 203]
  [141 160 203]
  [141 160 203]
  ...
  [117 152 202]
  [ 51  87 135]
  [ 11  49  97]]

 [[141 160 203]
  [141 160 203]
  [141 160 203]
  ...
  [116 151 201]
  [ 50  86 134]
  [ 11  49  97]]

 [[141 160 203]
  [141 160 203]
  [141 160 203]
  ...
  [115 151 199]
  [ 49  85 133]
  [ 10  48  96]]

 ...

 [[139  56   0]
  [138  58   0]
  [137  56   0]
  ...
  [ 95 101 108]
  [ 29  35  40]
  [ 25  32  35]]

 [[119  47   0]
  [119  48   0]
  [118  46   0]
  ...
  [ 54  60  67]
  [  5  11  16]
  [ 11  18  21]]

 [[112  45   0]
  [112  45   0]
  [109  44   0]
  ...
  [ 33  39  46]
  [  0   4   9]
  [ 11  18  21]]]


In [20]:
img = cv2.imread(r"WhatsApp Image 2024-08-30 at 10.03.11 PM.jpeg")
re_img = cv2.resize(img , (300 , 500))
h = np.hstack((re_img , re_img))
cv2.imshow("coder" , h)
cv2.waitKey(0)
cv2.destroyAllWindows() 
# cv2.destoryAllWindows()

In [24]:
img = cv2.imread(r"WhatsApp Image 2024-08-30 at 10.03.11 PM.jpeg")
re_img = cv2.resize(img , (300 , 300))
h = np.hstack((re_img , re_img , re_img))
v = np.vstack((h , h))
cv2.imshow("coder" , v)
cv2.waitKey(0)
cv2.destroyAllWindows() 
# cv2.destoryAllWindows()

In [9]:
list_name  = os.listdir(r"C:\Users\Mega Computers\Pictures")
list_name

['65f46cb7d78a4b3bd08029d9_65f46900f851c380fef1569a-c22a31c353f3dc41aed3dfc82e60072b.jpeg',
 'abstract-1920x1080-huawei-matebook-e-2019-hd-21829.jpg',
 'apple-1920x1080-fruit-autumn-4k-16216.jpg',
 'apples_branch_leaves_background_85594_3840x2160.jpg',
 'apple_branch_fruit_ripe_108947_3840x2160.jpg',
 'apricot-1920x1080-5k-15358.jpg',
 'banana_basket_fruit_77494_3840x2160.jpg',
 'banana_fruit_herbs_77493_3840x2160.jpg',
 'basket-fruit-1920x1080-lemon-lime-apple-grapes-strawberries-823.jpg',
 'berry_wild_berry_ripe_leaves_107784_3840x2160.jpg',
 'cake-2560x1440-strawberry-mint-berries-4425.jpg',
 'cake_cookies_dessert_raspberry_berry_lemon_93440_3840x2160.jpg',
 'Camera Roll',
 'cherries-1920x1080-delicious-4k-15366.jpg',
 'chris-ried-sqJ40H9RtNw-unsplash.jpg',
 'christian-joudrey-u_nsiSvPEak-unsplash.jpg',
 'chrysanthemum_flower_petals_118883_3840x2160.jpg',
 'cookies_pastries_shape_dessert_106708_3840x2160.jpg',
 'cupcake-1920x1080-fruits-raspberry-4148.jpg',
 'currant_berry_ripe_bran

In [ ]:
list_name  = os.listdir(r"C:\Users\Mega Computers\Pictures")

for name in list_name:
    path ="C:\\Users\\Mega Computers\\Pictures" 
    img_name = path + "\\" + name
    img = cv2.imread(img_name)
    img = cv2.resize(img , (500,600))
    cv2.imshow("slide Show " ,img)
    cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
import os
import cv2

# List all images in the specified directory
list_name = os.listdir(r"C:\Users\Mega Computers\Pictures")

for name in list_name:
    # Construct the full image path
    path = r"C:\Users\Mega Computers\Pictures"
    img_name = os.path.join(path, name)
    
    # Read the image
    img = cv2.imread(img_name)

    # Check if the image was read correctly
    if img is None:
        print(f"Error reading image: {img_name}. It may not be a supported format or the path could be incorrect.")
        continue

    # Resize the image
    img = cv2.resize(img, (500, 600))
    
    # Display the image in a window
    cv2.imshow("Slide Show", img)
    
    # Wait for 300 milliseconds
    cv2.waitKey(0)

# Close all OpenCV windows
cv2.destroyAllWindows()


Error reading image: C:\Users\Mega Computers\Pictures\Camera Roll. It may not be a supported format or the path could be incorrect.
Error reading image: C:\Users\Mega Computers\Pictures\desktop.ini. It may not be a supported format or the path could be incorrect.
Error reading image: C:\Users\Mega Computers\Pictures\pexels-hi-u-hoàng-668465.jpg. It may not be a supported format or the path could be incorrect.
Error reading image: C:\Users\Mega Computers\Pictures\Saved Pictures. It may not be a supported format or the path could be incorrect.
Error reading image: C:\Users\Mega Computers\Pictures\Screenshots. It may not be a supported format or the path could be incorrect.
